cores:
- name: Debug
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  minLevel: debug
  maxLevel: fatal
  urls:
  - /tmp/log/debug.log
- name: Info
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  minLevel: info
  maxLevel: fatal
  urls:
  - /tmp/log/info.log
- name: Warn
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  minLevel: warn
  maxLevel: fatal
  urls:
  - /tmp/log/warn.log
- name: Error
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  minLevel: error
  maxLevel: fatal
  urls:
  - /tmp/log/error.log
- name: Fatal
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  minLevel: panic
  maxLevel: fatal
  urls:
  - /tmp/log/fatal.log
- name: Access
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  minLevel: debug
  maxLevel: fatal
  urls:
  - /tmp/log/access.log
loggers:
- cores:
  - Debug
  - Info
  - Warn
  - Error
  - Fatal
- name: access
  cores:
  - Access
