level: debug
cores:
- name: Stderr
  encoding: console
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  minLevel: debug
  maxLevel: fatal
  urls:
  - stderr
loggers:
- stacktraceLevel: disable
  cores:
  - Stderr
