level: debug
loggers:
- stacktraceLevel: disable
  encoding: console
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
  outputs:
  - minLevel: debug
    maxLevel: fatal
    urls:
    - stderr
