loggers:
- encoding: json
  encoder:
    messageKey: msg
    levelKey: level
    timeKey: ts
    nameKey: logger
    callerKey: caller
    stacktraceKey: stacktrace
    levelEncoder: lowercase
    timeEncoder: epoch
  outputs:
  - minLevel: debug
    maxLevel: debug
    urls:
    - /tmp/log/debug.log
  - minLevel: info
    maxLevel: fatal
    urls:
    - /tmp/log/info.log
  - minLevel: warn
    maxLevel: fatal
    urls:
    - /tmp/log/warn.log
  - minLevel: error
    maxLevel: fatal
    urls:
    - /tmp/log/error.log
  - minLevel: panic
    maxLevel: fatal
    urls:
    - /tmp/log/fatal.log
