level: debug
cores:
- name: stderr
  encoding: console
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: string
    callerEncoder: short
    nameEncoder: full
  minLevel: debug
  maxLevel: fatal
  urls:
  - stderr
loggers:
- name: ""
  disableCaller: false
  stacktraceLevel: disable
  cores:
  - stderr
