level: debug
cores:
- name: Stderr
  encoding: console
  encoder:
    messageKey: M
    levelKey: L
    timeKey: T
    nameKey: "N"
    callerKey: C
    stacktraceKey: S
    levelEncoder: capitalColor
  minLevel: debug
  maxLevel: fatal
  urls:
  - stderr
loggers:
- cores:
  - Stderr
